version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    command: >
      sh -c "gradle test &&
             gradle allureReport --clean &&
             cp -rp /app/default-reports/allureReport/* /app/default-reports/latest/ &&
             rm -fR /app/default-reports/allureReport"
    restart: on-failure
    volumes:
      - shared-volume:/app/allure-results
      - shared-volume:/app/default-reports

  allure:
    image: "frankescobar/allure-docker-service"
    environment:
      CHECK_RESULTS_EVERY_SECONDS: NONE
      KEEP_HISTORY: NONE
    ports:
      - "5050:5050"
    depends_on:
      app:
        condition: service_completed_successfully
    volumes:
      - shared-volume:/app/allure-results
      - shared-volume:/app/default-reports

  allure-ui:
    image: "frankescobar/allure-docker-service-ui"
    environment:
      ALLURE_DOCKER_PUBLIC_API_URL: "http://localhost:5050"
      ALLURE_DOCKER_PUBLIC_API_URL_PREFIX: ""
    ports:
      - "5252:5252"
    depends_on:
      app:
        condition: service_completed_successfully
volumes:
  shared-volume:
